#!/bin/bash

# Installation file for funstore
# Coyright mLabs Research Inc., 2014


# Basic Settings ####
VERSION=v0.0.2
MODIFIED="Sept 15, 2014"
BINDIR=/usr/bin
fileName=`basename $0`
CURL="/usr/bin/curl"
PHP="/usr/bin/php5"
APACHE="/usr/sbin/apache2"
TEMPVAR=""

checkVersion()
{
    if [ "$BASH_VERSION" = '' ]; then
        clear
        printf "Error!!!\n\n\nPlease execute \"chmod +x "$fileName"\" and then run \"./"$fileName"\".  \n\n"
        exit
    fi
}

updateAptitude()
{
    echo "Updating Aptitude"
    sudo apt-get -y update
}

getCurl()
{
    if [ -f $CURL ];then echo ""
    else
       echo "$CURL command is not installed."
       echo "Running sudo apt-get install curl"
       sudo apt-get -y install curl
       TEMPVAR = "1";
    fi

    if [ "$TEMPVAR" = "1" ]; then exit; fi
}

getApache()
{
    if [ -f $APACHE ];then echo ""
    else
       echo "$APACHE command is not installed."
       echo "Running sudo apt-get install apache"
              sudo apt-get -y install apache2
       TEMPVAR = "1";
    fi

    if [ "$TEMPVAR" = "1" ]; then exit; fi
}

getPHP()
{
    if [ -f $PHP ];then echo ""
    else
       echo "$PHP command is not installed."
       echo "Running sudo apt-get install php"
       sudo apt-get install -y php5
       TEMPVAR = "1";
    fi

    if [ "$TEMPVAR" = "1" ]; then exit; fi
}

getDependencies()
{
sudo apt-get -y install libapache2-mod-php5 
sudo apt-get -y install libapache2-mod-perl2 
sudo apt-get -y install php5-cli 
sudo apt-get -y install php5-cgi
sudo apt-get -y install php5-common 
sudo apt-get -y install php5-curl 
sudo apt-get -y install php5-dev 
sudo apt-get -y install php5-gd
sudo apt-get -y install php5-imap 
sudo apt-get -y install php5-ldap 
sudo apt-get -y install php5-mhash 
sudo apt-get -y install php5-mysql 
sudo apt-get -y install php5-odbc
sudo apt-get -y install php5-sqlite
sudo apt-get -y install msmtp 
sudo apt-get -y install msmtp-mta 
sudo apt-get -y install ca-certificates
sudo apt-get -y install wget dos2unix
}

getNode()
{
wget http://node-arm.herokuapp.com/node_latest_armhf.deb 
sudo dpkg -i node_latest_armhf.deb
sudo rm node_latest_armhf.deb
sudo apt-get install -y build-essential python-dev python-rpi.gpio
}

funstoreSetup()
{
sudo ifdown wlan0
sudo ifup wlan0
cd /var/www
echo "We will get some files from internet to work for you"
sudo wget funstore.io/setup/`uname -n`/funstore.tar.gz
sudo tar -zxvf funstore.tar.gz
cd funstore/ajax
sudo touch tmpscript.sh
sudo chmod 775  tmpscript.sh
cd ..
}

editSudoer()
{
  sudo echo "\#\!bin/sh" > sudo-change
  sudo echo "www-data ALL=(ALL) NOPASSWD: ALL" >> sudo-change
  sudo chmod a+x sudo-change
}

getDashboard()
{
  cd /var/www/funstore
  sudo wget funstore.io/setup/`uname -n`/dashboard.tar.gz
  sudo tar -zxvf dashboard.tar.gz
}

getGrovePi()
{
  cd /var/www/funstore
  sudo git clone https://github.com/DexterInd/GrovePi
  cd GrovePi/Script
  sudo chmod +x install.sh
  sudo ./install.sh
}

getWolf()
{
  cd /var/www/funstore
  sudo git clone https://github.com/funstoreHQ/Wolf
  cd Wolf
  sudo chmod +x install.sh
  sudo ./install.sh
}

main()
{
clear
checkVersion
updateAptitude
getCurl
getApache
getPHP
getDependencies
getNode
funstoreSetup
editSudoer
reboot
getDashboard
getGrovePi
getWolf
}
main
